"""empty message

Revision ID: 52388701adf4
Revises: b73fa682b647
Create Date: 2025-11-05 16:55:55.917780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52388701adf4'
down_revision = 'b73fa682b647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'goal', ['goal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###
